# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: debian

pipelines:
  default:
    - step:
        script:
          - echo "Runs on branches that don't have specific pipeline."
  branches: # Container for all branch-specific pipelines.
    master:
      - step:
          script:
            - echo "Runs only on the master branch."
            - apt-get clean
            - apt-get update
            - apt-get -y --no-install-recommends install ant default-jdk dpkg-dev cdbs debhelper build-essential curl
            - dpkg-buildpackage -j2 -us -uc -b
            - pwd && ls -laR ../
            - curl -X POST "https://${BB_AUTH_STRING_SEC}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"`ls ../plantuml*.deb`"

